// Code generated by stream-rpc. DO NOT EDIT.
package proto

import (
	rpc "github.com/jibuji/go-stream-rpc"
)

type ServicePeerClient struct {
	peer *rpc.RpcPeer
}

func NewServicePeerClient(peer *rpc.RpcPeer) *ServicePeerClient {
	return &ServicePeerClient{peer: peer}
}

func (c *ServicePeerClient) FetchPeerList(req *PeerListRequest) *PeerListResponse {
	resp := &PeerListResponse{}
	err := c.peer.Call("ServicePeer.FetchPeerList", req, resp)
	if err != nil {
		return nil
	}
	return resp
}

func (c *ServicePeerClient) CheckService(req *ServiceCheckRequest) *ServiceCheckResponse {
	resp := &ServiceCheckResponse{}
	err := c.peer.Call("ServicePeer.CheckService", req, resp)
	if err != nil {
		return nil
	}
	return resp
}
